use ontomics::graph::ConceptGraph;
use ontomics::types::{EntityKind, PatternKind, RelationshipKind};

pub fn generate_ontology_md(graph: &ConceptGraph) -> String {
    let mut out = String::new();
    out.push_str(&render_header());
    out.push_str("\n\n");
    out.push_str(&render_concepts(graph));
    out.push_str("\n\n");
    out.push_str(&render_conventions(graph));
    out.push_str("\n\n");
    out.push_str(&render_abbreviations(graph));
    out.push_str("\n\n");
    out.push_str(&render_entities(graph));
    out.push_str("\n\n");
    out.push_str(&render_relationships(graph));
    out
}

fn render_header() -> String {
    "# ONTOLOGY.md\n\n\
     This file was generated by [ontomics](https://github.com/etiennechollet/ontomics). \
     It describes the domain vocabulary, naming conventions, and key entities of this codebase."
        .to_string()
}

fn render_concepts(graph: &ConceptGraph) -> String {
    let mut concepts: Vec<_> = graph.concepts.values().collect();
    concepts.sort_by(|a, b| b.occurrences.len().cmp(&a.occurrences.len()));

    let mut out = "## Domain Concepts\n\n".to_string();
    if concepts.is_empty() {
        out.push_str("No concepts detected.\n");
        return out;
    }

    out.push_str("| Concept | Occurrences | Cluster |\n");
    out.push_str("|---------|-------------|--------|\n");

    for concept in concepts.iter().take(20) {
        let cluster = concept
            .cluster_id
            .map(|id| id.to_string())
            .unwrap_or_else(|| "—".to_string());
        out.push_str(&format!(
            "| `{}` | {} | {} |\n",
            concept.canonical,
            concept.occurrences.len(),
            cluster,
        ));
    }
    out
}

fn render_conventions(graph: &ConceptGraph) -> String {
    let conventions = graph.list_conventions();

    let mut out = "## Naming Conventions\n\n".to_string();
    if conventions.is_empty() {
        out.push_str("No naming conventions detected.\n");
        return out;
    }

    out.push_str("| Pattern | Type | Role | Examples | Frequency |\n");
    out.push_str("|---------|------|------|----------|-----------|\n");

    for conv in conventions {
        let pattern = match &conv.pattern {
            PatternKind::Prefix(p) => format!("prefix `{p}_`"),
            PatternKind::Suffix(s) => format!("suffix `_{s}`"),
            PatternKind::Compound(c) => format!("compound `{c}`"),
            PatternKind::Conversion(c) => format!("conversion `{c}`"),
        };
        let examples = conv.examples.iter().take(3).map(|s| format!("`{s}`")).collect::<Vec<_>>().join(", ");
        out.push_str(&format!(
            "| {} | {:?} | {} | {} | {} |\n",
            pattern,
            conv.entity_type,
            conv.semantic_role,
            examples,
            conv.frequency,
        ));
    }
    out
}

fn render_abbreviations(graph: &ConceptGraph) -> String {
    let abbreviations: Vec<(String, String)> = graph
        .relationships
        .iter()
        .filter(|r| r.kind == RelationshipKind::AbbreviationOf)
        .filter_map(|r| {
            let short = graph.concepts.get(&r.source).map(|c| c.canonical.clone())?;
            let long = graph.concepts.get(&r.target).map(|c| c.canonical.clone())?;
            Some((short, long))
        })
        .collect();

    let mut out = "## Abbreviations\n\n".to_string();
    if abbreviations.is_empty() {
        out.push_str("No abbreviations detected.\n");
        return out;
    }

    out.push_str("| Short | Long |\n");
    out.push_str("|-------|------|\n");
    for (short, long) in &abbreviations {
        out.push_str(&format!("| `{short}` | `{long}` |\n"));
    }
    out
}

fn render_entities(graph: &ConceptGraph) -> String {
    let mut scored: Vec<_> = graph
        .entities
        .values()
        .map(|entity| {
            let score = graph.centrality.get(&entity.id).map(|c| c.pagerank).unwrap_or(0.0);
            (entity, score)
        })
        .collect();
    scored.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));

    let mut out = "## Key Entities\n\n".to_string();
    if scored.is_empty() {
        out.push_str("No entities detected.\n");
        return out;
    }

    out.push_str("| Entity | Kind | Role | PageRank |\n");
    out.push_str("|--------|------|------|----------|\n");

    for (entity, pagerank) in scored.iter().take(20) {
        let kind = match entity.kind {
            EntityKind::Function => "function",
            EntityKind::Class => "class",
            EntityKind::Method => "method",
        };
        out.push_str(&format!(
            "| `{}` | {} | {} | {:.4} |\n",
            entity.name, kind, entity.semantic_role, pagerank,
        ));
    }
    out
}

fn render_relationships(graph: &ConceptGraph) -> String {
    let mut co_occurrences: Vec<_> = graph
        .relationships
        .iter()
        .filter(|r| r.kind == RelationshipKind::CoOccurs)
        .filter_map(|r| {
            let source = graph.concepts.get(&r.source).map(|c| c.canonical.as_str())?;
            let target = graph.concepts.get(&r.target).map(|c| c.canonical.as_str())?;
            Some((source, target, r.weight))
        })
        .collect();
    co_occurrences.sort_by(|a, b| b.2.partial_cmp(&a.2).unwrap_or(std::cmp::Ordering::Equal));

    let mut out = "## Relationships\n\n".to_string();
    if co_occurrences.is_empty() {
        out.push_str("No co-occurrence relationships detected.\n");
        return out;
    }

    out.push_str("| Concept A | Concept B | Co-occurrence Weight |\n");
    out.push_str("|-----------|-----------|---------------------|\n");

    for (source, target, weight) in co_occurrences.iter().take(20) {
        out.push_str(&format!("| `{source}` | `{target}` | {weight:.4} |\n"));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_header_contains_title() {
        let header = render_header();
        assert!(header.contains("ONTOLOGY.md"));
        assert!(header.contains("ontomics"));
    }

    #[test]
    fn generate_on_empty_graph_does_not_panic() {
        let graph = ConceptGraph::empty();
        let md = generate_ontology_md(&graph);
        assert!(md.contains("# ONTOLOGY.md"));
        assert!(md.contains("## Domain Concepts"));
        assert!(md.contains("## Naming Conventions"));
        assert!(md.contains("## Abbreviations"));
        assert!(md.contains("## Key Entities"));
        assert!(md.contains("## Relationships"));
    }

    #[test]
    fn empty_graph_shows_no_data_messages() {
        let graph = ConceptGraph::empty();
        let md = generate_ontology_md(&graph);
        assert!(md.contains("No concepts detected."));
        assert!(md.contains("No naming conventions detected."));
        assert!(md.contains("No abbreviations detected."));
        assert!(md.contains("No entities detected."));
        assert!(md.contains("No co-occurrence relationships detected."));
    }
}
